# \u6307\u5B9A\u9879\u76EE\u7AEF\u53E3\u53F7
server.port=8888
# \u6307\u5B9A\u9879\u76EE\u524D\u7F00
server.servlet.context-path=/shiro
# \u6307\u5B9A\u9879\u76EE\u540D
spring.application.name=shiro

# \u5C06\u9ED8\u8BA4\u7684thymleaf\u66F4\u6362\u4E3Ajsp
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp

# \u6570\u636E\u5E93\u76F8\u5173\u914D\u7F6E
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.url=jdbc:mysql://localhost:3306/shiro?characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=123456

mybatis.type-aliases-package=com.yibao.springbootshiro.entity
mybatis.mapper-locations=classpath:com/yibao/mapper/*.xml

# Redis
spring.redis.port=6379
spring.redis.host=localhost
spring.redis.database=0





